apiVersion: v1
kind: ServiceAccount
metadata:
  name: curljob2
  
---
apiVersion: batch/v1
kind: Job
metadata:
  name: curl2
spec:
  template:
    spec:
      serviceAccountName: curljob2
      containers:
        - name: curl2
          image: curlimages/curl
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command:
            - '/bin/sh'
            - '-ec'
            - |
              export CONSUL_HTTP_ADDR="${HOST_IP}:8501"
          command: [ 'sh', '-c']
          args:
            - curl -k https://${HOST_IP}:8501/v1/catalog/services 
      restartPolicy: Never
    metadata: 
      annotations:
        consul.hashicorp.com/connect-inject: "false"

  backoffLimit: 4

---

