apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: static-client-2-server
spec:
  destination:
    name: static-server 
  sources:
    - name: static-client 
      action: allow
